# Generated by Django 2.0.7 on 2018-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snipper',
            new_name='Snippet',
        ),
    ]
